# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Oktagono Properties
email: info@oktagonoproperties.com
phone: +30 2311 268824
mobile: +30 6973525751 
logo: "<img src='/assets/img/logo-oktagonoproperties.png' alt='logo' class='img-responsive'>"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
info:
  - contact: Επικοινωνία
  - related: Σχετικά ακήνιτα

nav:
  
- title: 
    el: Αρχική 
    en: Home 
  url: /
  class: ti-home
- title: 
    el: Ακίνητα
    en: Properties
  url: /properties.html
  class:  ti-list-ol
- title: 
    el: Επικοινωνία
    en: Contact
  url: /contact.html
  class: ti-email

# Build settings
plugins:
  - jekyll-multiple-languages-plugin

collections:
  properties:
    output: true

languages: ["el", "en"]
exclude_from_localizations: ["assets", "javascript",  "images", "css"]
language_default: 'el'
languageNames:
  el: Ελληνικά
  en: English
